// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package worker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StartServiceClient is the client API for StartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StartServiceClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
}

type startServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStartServiceClient(cc grpc.ClientConnInterface) StartServiceClient {
	return &startServiceClient{cc}
}

func (c *startServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/worker.StartService/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StartServiceServer is the server API for StartService service.
// All implementations must embed UnimplementedStartServiceServer
// for forward compatibility
type StartServiceServer interface {
	Start(context.Context, *StartRequest) (*StartResponse, error)
	mustEmbedUnimplementedStartServiceServer()
}

// UnimplementedStartServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStartServiceServer struct {
}

func (UnimplementedStartServiceServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedStartServiceServer) mustEmbedUnimplementedStartServiceServer() {}

// UnsafeStartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StartServiceServer will
// result in compilation errors.
type UnsafeStartServiceServer interface {
	mustEmbedUnimplementedStartServiceServer()
}

func RegisterStartServiceServer(s grpc.ServiceRegistrar, srv StartServiceServer) {
	s.RegisterService(&StartService_ServiceDesc, srv)
}

func _StartService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StartServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker.StartService/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StartServiceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StartService_ServiceDesc is the grpc.ServiceDesc for StartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.StartService",
	HandlerType: (*StartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _StartService_Start_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "start.proto",
}
